version: '3.9'

services:
  staging_db:
    container_name: staging_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=satish
      - POSTGRES_PASSWORD=satishwoodworks
    volumes: 
      - db:/var/lib/postgresql/data
  
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  server:
    container_name: api
    image: server
    build: .
    command: python main.py
    # command: gunicorn -b 0.0.0.0:8000 todosapp.wsgi:application
    depends_on:
      - staging_db
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app

volumes:
  db:
    driver: local